### ISSUE TITLE
Art: Hacker character ('Drake')

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1388] opened 2021-07-22 01:12 UTC
![img](https://i.imgur.com/ioplEDt.jpg)
![img](https://i.imgur.com/GwfvBI0.jpg)
![img](https://i.imgur.com/r5d0YlJ.jpg)

Description: A hacker from Zone 0. He waits for drop storms to attract a drop hunter, then snipes them out of the sky with his arsenal of hacked guns. He steals their drops, then uses the drop hunter’s reputation to sell the stolen goods for Silk. He also works jobs for the Zero Syndicate, a lighthearted lulz group funded by ransomware. He has a small platoon of henchmen that he can call in to perform his dirty work and to guard his stash.

He uses an arsenal of guns, most commonly SMGs.

![img](https://vroid-hub.pximg.net/c/1200x1600_a2_g5/images/full_body_images/1174289/2170268772612634239.png)

Can be based on Kanji model for the face style and possibly the hair. I don't know whether or not our Kanji rendition is a good place to start.

Kanji was purchased and should be in the GDrive. It seems to not be on booth anymore but it is a non-downloadable from Vroid Hub.

https://booth.pm/en/items/1880254
https://hub.vroid.com/en/characters/8708676096431470179/models/3441778242791612085

- - -
The main thing here seems like having a cool jacket, with some sort of cool collar, and being a male, orange (opposite colors), more evil version of Scillia.

**Comment by GaladWarder** [comment] 2021-07-22 14:24
Awesome - I can work with that! Will be fun to make a more 'evil' character.

With the guns, are they straight-up SMG's, or are they needing to be slightly cartooned/stylized, kind of like the earlier rifle models Dream made? Not sure how literal the weapons in this universe need to be.

Using Kanji as a base should work well, I think he just needs a bit of clothing design to make him look more dangerous and less 'petulant'.

**Comment by Vianvolaeus** [comment] 2021-07-22 14:27
Seems the creator pulled everything from their booth, but some of their models including this one is on sketchfab for viewing only (https://sketchfab.com/kasamoto)

Just gonna throw this out there as well - we can have floating holsters and rigs for weapons and things like that, a bit like the original model that was originally concepted from did.

**Comment by avaer** [comment] 2021-07-22 22:01
> With the guns, are they straight-up SMG's, or are they needing to be slightly cartooned/stylized, kind of like the earlier rifle models Dream made? Not sure how literal the weapons in this universe need to be.

These weapons are all made inside the world by random people, so if it's something a modeler would model it makes sense. It's mostly about consistency with the chara (e.g. in texture style), and consistency with other weapons. In which case they make more sense cartoony.

> Just gonna throw this out there as well - we can have floating holsters and rigs for weapons and things like that, a bit like the original model that was originally concepted from did.

Yes, that's similar to the vibe I was thinking. The idea I had is somewhat like Neo, where they are both SMGs, and come with tactical holsters at the side and perhaps extra magazines.

![image](https://user-images.githubusercontent.com/6926057/126714414-c2572dd3-95cc-40d2-a4f9-ff687e63efe0.png)

**Comment by GaladWarder** [comment] 2021-07-28 23:28
Took a pass at this, here's a V1:

![Hacker_FilterClothing_V1](https://user-images.githubusercontent.com/29031531/127409002-ea13e964-837a-42dd-b667-6c37e195f368.jpg)

**Comment by avaer** [comment] 2021-07-29 00:29
It's capturing the right themes, the animated showdown would be very fun.

![image](https://user-images.githubusercontent.com/6926057/127411001-f2f93fdd-74f2-4594-b859-8ff469ed426a.png)

![image](https://user-images.githubusercontent.com/6926057/127409889-e1da2315-d6f9-49c5-8f9f-9c8d0122f1c4.png)

:D 👍 

![image](https://user-images.githubusercontent.com/6926057/127409921-38cadf9a-f9cb-428a-9aca-75a91a1afe9b.png)

IMO the look is a bit too feminine/Japanese fashion, and we should take the hood off. There's nothing stylistic wrong with any of that, but I'd like to increase the delta to Scilly. One way to do that would be prominent spiky masculine hair.

I'm thinking mainly in terms of the showdown -- the poses and faces in these concepts should have a parallel.

![image](https://user-images.githubusercontent.com/6926057/127411707-563e9e3a-dc43-49e9-aca7-3e04313ba5c3.png)
![image](https://user-images.githubusercontent.com/6926057/127413062-e84ff067-01ca-4180-ad74-08b3a4b2bae3.png)

![image](https://user-images.githubusercontent.com/6926057/127412557-a6e4a974-5ad9-4ca0-8104-ac66cff824c0.png)

Gear like this feels a bit too inelegant to be used in combat. Control equipment does feel appropriate, but it would be more small  and simple, for controlling the breathing mask, rather than a computer attached to your waist. I think these characters can canonically just pull out their table computers at any time so having extra computers equipped would be redundant.

The more I think about it, IMO we just need a remixed version of the first reference. Different hair (less impossible/cartoony), different pose, different gear arrangement, but in the same vein. But the source material feels appropriate and has all of the elements.

![image](https://user-images.githubusercontent.com/6926057/127412066-f54a2c25-615d-45c4-8899-ed4788ed2656.png)

**Comment by GaladWarder** [comment] 2021-07-29 03:44
Cool, no problem! I'll take another pass at it tomorrow, this all makes sense to me!

**Comment by GaladWarder** [comment] 2021-07-31 04:32
Took another pass at this; leaned more heavily on the ingredients in the initial reference art posted, just changing the style and fleshing out the details. 

Can't get the image to upload, so here's a  Drive link: https://drive.google.com/open?id=1jODYW3KWmpBpuVtH1P1ioTxLXMbaMmgu&authuser=GaladDota%40yahoo.com&usp=drive_fs

**Comment by avaer** [comment] 2021-07-31 07:12
![Hacker](https://user-images.githubusercontent.com/6926057/127731901-c14c6587-2569-4bf0-a15c-c9e699a7aa82.png)

Looks great! I don't have any design changes to recommend. We should just sketch this with similar line/color fidelity to the Scillia concept -- I think that's the format we should have all of the characters in, cartoony and flat, bordering on the line of western vs anime, because that is a good ground truth for artistic interpretations.

**Comment by avaer** [comment] 2021-07-31 07:15
I like both jackets, which do seem like they could be the same brand as Scillia's.

**Comment by avaer** [comment] 2021-07-31 07:17
I think this is good enough to restart the modeling, though MC comes first.

**Comment by GaladWarder** [comment] 2021-08-03 05:39
Done in similar line/color style to the Scilia concept - I'm not totally sold on the colors and values, but they are masked so they can be changed extremely easily.

![Hacker_FilterClothing_V3](https://user-images.githubusercontent.com/29031531/127963675-1e00cbd6-98be-413a-b335-0768564e93db.jpg)

**Comment by GaladWarder** [comment] 2021-08-06 05:33
Ortho sheet finished. A few notes:

- Used the Vroid base for Kanji to work off of, almost all proportions match either exactly or are very close
- The side ortho is not 100% accurate; some of those forms are too complex to accurately visualize in 2d. I got them as close as I can, but there will be some variance there to make the geo work.
- The front orthos should be very accurate, they are all gridded out and transferred from the perspective view.
- The eyes have been changed to look more 'evil', but I tried to keep the changes minimal to not break blendshapes.

![Hacker_Orthos](https://user-images.githubusercontent.com/29031531/128461012-645408cf-d1fb-4188-86df-160769b994c5.jpg)

**Comment by avaer** [comment] 2021-08-07 12:01
Hm I don’t think the jacket should pop back like that. I think it should feel more like it is hanging down rather than than it being stuck out via wire, though it is ok to keep it large and bulky.

In the concept, my interpretation was that the jacket was blowing in the wind but would probably drop down otherwise.

**Comment by avaer** [comment] 2021-08-07 12:14
I think there’s a lot of opportunity to add interesting color to reach Scillia’s complexity.

We could use orange to accent the dark in some geometric design, rather than making it the bulk color. Also I think the orange could be brighter.

The pants and jacket should probably have different and more interesting colors, like some sort of leather on the jacket and camo on the pants. It’s slightly too clean otherwise. The brand could still be 0x.

**Comment by avaer** [comment] 2021-08-07 12:21
Evil is fine, but the eyes should be more opened/larger like Scillia’s. I was able to get quite good eyes out of the original kanji. Will post what I think are appropriate expressions.

**Comment by avaer** [comment] 2021-08-07 14:52
![image](https://user-images.githubusercontent.com/6926057/128604199-92b847fa-7bc1-4620-8105-ae0e75de446e.png)
![image](https://user-images.githubusercontent.com/6926057/128602142-7a54851e-6543-4787-9518-085c20cd7ff9.png)
![image](https://user-images.githubusercontent.com/6926057/128602230-36599f5e-9678-47c0-9de3-d0a398a09e69.png)
![image](https://user-images.githubusercontent.com/6926057/128602388-bb54c190-b7dd-4ced-b986-ff85942ddd37.png)
![image](https://user-images.githubusercontent.com/6926057/128603666-9e2ba161-671a-400d-a2cd-09d23a3c269a.png)
![image](https://user-images.githubusercontent.com/6926057/128603949-4dd56f8b-9c58-431f-b6e7-a67d3f9abcda.png)
![image](https://user-images.githubusercontent.com/6926057/128604074-0b76e508-8b07-4bd5-8a84-0f61a97c0758.png)

**Comment by GaladWarder** [comment] 2021-08-07 18:38
> Hm I don’t think the jacket should pop back like that. I think it should feel more like it is hanging down rather than than it being stuck out via wire, though it is ok to keep it large and bulky.

Correct - these are modelling orthos, so it's been stuck out like that purely for modeling purposes. Once it's rigged, it will hang naturally.

> I think there’s a lot of opportunity to add interesting color to reach Scillia’s complexity.
We could use orange to accent the dark in some geometric design, rather than making it the bulk color. Also I think the orange could be brighter.
The pants and jacket should probably have different and more interesting colors, like some sort of leather on the jacket and camo on the pants. It’s slightly too clean otherwise. The brand could still be 0x.

Agreed, I'm not sold on the colors. I plan to circle back around on them and do some iteration to get them feeling better. I think all the patterning is working, so there's enough there to model from though. As long as you're happy with the base design, the colors are easily tweaked.

> I was able to get quite good eyes out of the original kanji. Will post what I think are appropriate expressions.

I based the proportions off of the original Kanji, so if you are happy with the eyes as they are on the actual model, I'd propose we just keep them. No reason to reinvent the wheel if it's working, plus I assume it'll make Vian's life much easier than doing a facial redesign.

**Comment by avaer** [comment] 2021-08-07 19:26
Ok thank you that clears it up.

I don’t have any other comments, we could model it.

**Comment by avaer** [comment] 2021-08-07 19:26
@madjin so expressed interest in bashing here.

**Comment by madjin** [comment] 2021-08-13 15:51
Current pureref for character Drake:

![drake2](https://user-images.githubusercontent.com/32600939/129385605-63db5d66-5d3f-442b-9373-77ddfb3f067b.png)
https://cdn.discordapp.com/attachments/641036402829819914/875768028783054878/drake.pur

**Comment by avaer** [comment] 2021-08-19 23:44
Modeling progress:

![](https://cdn.discordapp.com/attachments/876852048363151360/877973884303990874/unknown.png)

**Comment by avaer** [comment] 2021-08-19 23:48
Other than the jacket, it's mostly the coloring that needs work; the original did not have strong colors yet and that is slightly weakened in the model lighting.

**Comment by Vianvolaeus** [comment] 2021-08-23 17:06
![image](https://user-images.githubusercontent.com/80061436/130487765-2292fd62-f461-4bfc-b047-03f5e256a1bb.png)

Updated textures following 'poison frog' input previously.

Modelled holster, midway on textures.

Mostly finished on other accessories.

Made an extra texture set for the jeans - one has fake 'skin' showing through the tears but is one uniform model, the other has opacity for showing an actual body underneath.

**Comment by Vianvolaeus** [comment] 2021-08-23 17:09
speckling / digi effect that's only really noticable up close, so it works as detail without making it too hard to draw / recall from memory: 
![image](https://user-images.githubusercontent.com/80061436/130488110-17935cf8-85d0-4ec0-9a2b-d7c19a579935.png)

Similar idea for the rear jacket: 
![image](https://user-images.githubusercontent.com/80061436/130488258-f988b9a4-5042-4af2-a05e-ae808fe359c4.png)

Pistol, previously done:

![image](https://user-images.githubusercontent.com/80061436/130488377-559fb29c-c50e-4ebf-92e8-c94cdaf3f385.png)

**Comment by Vianvolaeus** [comment] 2021-08-25 16:33
![image](https://user-images.githubusercontent.com/80061436/130829610-7c9b828c-0e43-4520-9d68-6f47b2604507.png)

Full mat pass. Rigging mostly done for body, need to match rear jacket up to main armature

label from belt is seperately rigged, will use collisions 

Can remove a lot of underlying body geo once we're confirmed on things, should reduce poly count a fair bit

**Comment by avaer** [comment] 2021-08-28 06:13
This looks really high quality, especially the body/gear, but my gut says we need another take on the hair and jacket.

It’s gotten pretty dark cyberpunk and increasingly far from my impression of how this character is supposed to behave in the script (a more intelligent and funny Gary, mildly threatening, glad to play pranks and troll, but not uncomfortable to be around).

The hair might benefit from being less crazy, and the eyes could be more of a trickster rather than a soldier. And now that it’s shown in the model think we can do a better jacket. It does feel like this character should have something on the back but the jacket doesn’t read clean in 3D (there is a lot going on). There must be some other object that would make more intuitive/visceral sense there but my mind is drawing a blank without doing another round on Pinterest.

**Comment by Vianvolaeus** [comment] 2021-08-30 12:50
Only thing I can really think and find that's interesting would be something like a shoulder cape, but it feels a bit too cyber and gunslinger esque. 

![image](https://user-images.githubusercontent.com/80061436/131340915-56a44374-0653-44c8-9cdc-e96f79520ece.png)

Speaking directly on the pokemon trainer / Gary pointers, looks like one of the pokemon elites in recent years had a cape like this? It's a bit regal , would probably serve better being more basic (and damaged?)

**Comment by Vianvolaeus** [comment] 2021-08-30 13:52
Dialed back a bit on the facial geo, made brows less aggressive
![image](https://user-images.githubusercontent.com/80061436/131349978-6e368014-6ccc-4462-9c98-661a8fa6a412.png)


Few more hairstyle options...

![image](https://user-images.githubusercontent.com/80061436/131349939-a5481b56-eaf5-4005-bc71-ea42569707fa.png)

**Comment by Vianvolaeus** [comment] 2021-08-30 14:18
![image](https://user-images.githubusercontent.com/80061436/131353758-c40af064-16a5-4f4f-a436-3f289322aa71.png)

Side cloak test. Not happy with it, but logging the test nonetheless.

**Comment by Vianvolaeus** [comment] 2021-08-30 14:31
Regular cape: 

![image](https://user-images.githubusercontent.com/80061436/131355623-db027ad1-82cd-4334-a4c0-4486e73e06ce.png)

**Comment by Vianvolaeus** [comment] 2021-08-30 14:43
![image](https://user-images.githubusercontent.com/80061436/131357449-232fbe5e-6f16-4925-a0e1-24cb5f51f6fb.png)

alternative with a rear collar-like shape

**Comment by Vianvolaeus** [comment] 2021-08-30 17:02
> another take on the hair and jacket

Which jacket? The inner one, or the one on the back? 

Gonna assume these aren't any good or what's now envisioned, so I suggest we go back to concepting again since it's not visually clear what's actually being desired at this point? It was suggested to make it more edgy and add weapons, etc, which was done, but now it's too cyberpunk as a result? Considering the character at large is the same (added weapons, changed hair / face), I don't think the rest of the design is any more off track now than what was previously OK'd further up. 

In terms of back attachments or props, if it's not exclusively visual flair then we need to lean into the character more, which will need some prop design and thought put into it first rather than shotgunning it, so we can make something visually cohesive. 

Character is [driven by a motivation to collect silk](https://github.com/webaverse/app/issues/1388#issuecomment-898558006), so we could reference something in world - stolen silk fountain pieces, broken origin tablet, etc.

Could also reference something else in the character - zero syndicate might be a good thing to flesh out as it can be referenced in other lore and environments

**Comment by Vianvolaeus** [comment] 2021-08-30 17:10
![image](https://user-images.githubusercontent.com/80061436/131377495-3f1b2caa-77df-4262-921c-4f8318434a71.png)
Just a rough idea based on that, having some kind of zero syndicate logo on a small flaired cape. It's suggesting they're representing something, but with a minimalistic logo it's not too intrusive to the rest of the design.

**Comment by GaladWarder** [comment] 2021-08-31 00:02
Took a swing at a few other options for facial redesign as discussed in the meeting.

The top row are what I would consider 'minor' changes - proportion and shape changes that only slightly alter the feel and expression.

The bottom row are 'major' changes - changes that will read as a completely different character.

I used the tousled hair that Via uploaded earlier; I think it's the best for a sort of 'trickster youth' vibe.

![Hacker_FacialProportions_V1](https://user-images.githubusercontent.com/29031531/131420574-e22f954e-0e8d-4f32-9091-ba84284473fb.jpg)

A few other things to consider - I think that the 'cyberpunk' vibe is coming mostly from colors and lighting; I would propose messing with those first before considering any large redesigns of the meshes. Another thing that could be useful would be playing with the proportions of the accessories - such as weapons. Making them 15% larger, for example, will kick it out of the 'cyberpunk' vibe and into stylization.

In a similar vein, we could try just cutting the sleeves from the current jacket over the shoulder - looking at the screenshots I think that's what is messing with the 'epic' feel. I was using them to break silhouette in 2D but I think that was an error on my part - it only breaks it correctly from a few angles. If the sleeves are removed it will feel more like a shoulder cape, which I think may work well without losing any shape language. 

Just a thought, may be worth trying if it's fast. I really liked the ideas brought up in the meeting too - tying it more into the lore - so if that's the direction we want to go I will happily take a concept pass at it, just let me know what you need @Vianvolaeus

**Comment by Vianvolaeus** [comment] 2021-08-31 13:15
Testing with rolled up / short sleeves on the old jacket, bit more volume on it, with the above hair. Don't think it's working, going to focus on back item ideas since head isn't confirmed yet. 
![image](https://user-images.githubusercontent.com/80061436/131508285-044ce146-fe6f-450f-aeda-6c267f228400.png)

**Comment by Vianvolaeus** [comment] 2021-08-31 16:09
Multires'd a cloak for more detail.

Found the (wonderfully convoluted) way of bringing custom fonts into Substance Painter, so we can bring anything in.

I've picked out this one in particular since a) very stylized b) the 0 and 'o' character resemble the unicode missing/unsupported character square, while still retaining the zero shape, it's a little obtuse. Thought it has a good tie in with the idea of a disruptive shadow / hacker group. 

![image](https://user-images.githubusercontent.com/80061436/131537468-46c1a176-89e0-4a20-ae1b-75f7a8196fb9.png)

**Comment by Vianvolaeus** [comment] 2021-08-31 16:12
![image](https://user-images.githubusercontent.com/80061436/131538480-6da2e0cc-107e-4814-a9fb-f6ce1ce82bfd.png)

**Comment by Vianvolaeus** [comment] 2021-08-31 16:15
![image](https://user-images.githubusercontent.com/80061436/131538805-cc3d67e9-4679-4e8a-918d-b40b6493cc60.png)
Gives a nice rounded triangular shaped silhouette in which the shotgun can be hidden from direct view

**Comment by Vianvolaeus** [comment] 2021-08-31 16:17
We do have other jacket colors if we want lighter variations to avoid being too dark overall: 
![image](https://user-images.githubusercontent.com/80061436/131539121-7209f57c-21ae-4af8-804d-035550b0f3a7.png)

**Comment by Vianvolaeus** [comment] 2021-08-31 16:48
![image](https://user-images.githubusercontent.com/80061436/131543319-3f018ee4-eb48-4d0e-b664-edd16f80dfed.png)

some of the faces, hopefully will help picking one out since I'm still blocked on that. 

These are fast but destructive edits - shapekeys broken intentionally just to get a visual out.

**Comment by GaladWarder** [comment] 2021-08-31 16:53
I really liked your idea of having a piece of the Origin Tablets on his back, the original concepts all had some little chunks missing from them, and I think it makes sense. The origin-zero shawl thing looks pretty slick too; I like the material on it especially.

I was thinking about this more last night, and another thought I had would be what if he had like a stylized 'hacking rig' as a backpack? Terminal with keyboard, maybe an interesting looking jack to connect to hardware, antennae, etc... Kind of like the Gargoyles in Snow Crash. That would give an interesting silhouette and also keep to the vibe of the character.

I'll be able to make some concepts if you need, but it may be a day or so; I'm working on the hero images currently and they're gonna take up a good chunk of time, I think. I could make a slot tomorrow morning to come up with some backpack ideas though if you need visuals, just let me know!

**Comment by GaladWarder** [comment] 2021-08-31 16:55
I had a rig in the V1 concept for Drake which could be used as ref too - it was attached to his leg, but given some upsizing and tweaking it could easily be a backpack, especially if it had some 'modules' added to it, or some hardsurface greebles:

![image](https://user-images.githubusercontent.com/29031531/131544449-11931d3a-e330-4f8b-b342-5aa90bb939cd.png)

**Comment by Vianvolaeus** [comment] 2021-09-01 11:56
I like the ideas, but they might be a bit low-tech and bulky for the considering the rest of the char. I think we have a keyboard asset stashed, so I can chuck that in and try it either way though 👍 

I believe this is considered (close to) finished after looking at the variants of everything that's been made. @avaer should be able to explain the idea for generative avatars. 

I'm cleaning up  .blend file and getting at least a variation ready today

**Comment by Vianvolaeus** [comment] 2021-09-01 14:43
There's a cleaned up blend file with a variation ready for use in Blender / copying to other scenes ready here: 
https://drive.google.com/drive/folders/1TamnUl-qxQbaTN_PrwTbqE5qwun5yAyh

**Comment by GaladWarder** [comment] 2021-09-01 18:17
Awesome, that means I can use it as a mannequin in some of the hero images!

> I like the ideas, but they might be a bit low-tech and bulky for the considering the rest of the char. I think we have a keyboard asset stashed, so I can chuck that in and try it either way though 👍

Makes sense to me, I'll keep thinking about it and let you know if I come up with other ideas that may fit better. I'd imagine that since it's an accessory, it can be pretty easily swapped out as needed

**Comment by NotFuji** [comment] 2021-10-04 17:47
![drake_v4](https://user-images.githubusercontent.com/38316883/135899171-7f9bcfa6-8de2-424c-b956-1f8ff047216b.png)

**Closed** 2022-11-04 12:39 UTC
Labels: in progress, p1, design
