### ISSUE TITLE
Character cannot move in plaza.scn

### ISSUE THREAD

**Issue by ahadshams** [webaverse/app#2977] opened 2022-05-12 08:09 UTC
@alisaad673 pls test and expand

**Comment by ahadshams** [comment] 2022-05-12 09:10
not able to reproduce.. hmmm

**Comment by alisaad673** [comment] 2022-05-18 17:22
Not able to reproduce. This is working fine. Was probably because of scene not loading properly.
Closing

**Closed by alisaad673** 2022-05-18 17:22 UTC
